-- Generated by draw2sql
-- Flavor: postgres
-- Generated UTC: 2026-02-22T17:09:25.815Z


-- 1) Create missing tables

CREATE TABLE IF NOT EXISTS "Provider" (
  "ID" uuid NOT NULL,
  "Slug" text,
  "Name" text,
  "IsActive" boolean,
  "CreatedAt" timestamptz,
  PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS "ProviderAccount" (
  "ID" uuid NOT NULL,
  "ProviderId" uuid,
  "AccountKey" text,
  "DisplayName" text,
  "ExternalAccountId" text,
  "IsActive" boolean,
  PRIMARY KEY ("ID")
);


-- 2) Add missing columns

ALTER TABLE "Provider" ADD COLUMN IF NOT EXISTS "ID" uuid NOT NULL;

ALTER TABLE "Provider" ADD COLUMN IF NOT EXISTS "Slug" text;

ALTER TABLE "Provider" ADD COLUMN IF NOT EXISTS "Name" text;

ALTER TABLE "Provider" ADD COLUMN IF NOT EXISTS "IsActive" boolean;

ALTER TABLE "Provider" ADD COLUMN IF NOT EXISTS "CreatedAt" timestamptz;

ALTER TABLE "ProviderAccount" ADD COLUMN IF NOT EXISTS "ID" uuid NOT NULL;

ALTER TABLE "ProviderAccount" ADD COLUMN IF NOT EXISTS "ProviderId" uuid;

ALTER TABLE "ProviderAccount" ADD COLUMN IF NOT EXISTS "AccountKey" text;

ALTER TABLE "ProviderAccount" ADD COLUMN IF NOT EXISTS "DisplayName" text;

ALTER TABLE "ProviderAccount" ADD COLUMN IF NOT EXISTS "ExternalAccountId" text;

ALTER TABLE "ProviderAccount" ADD COLUMN IF NOT EXISTS "IsActive" boolean;


-- 3) Add foreign keys where inferred

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ProviderAccount_ProviderId_Provider_ID') THEN
    ALTER TABLE "ProviderAccount" ADD CONSTRAINT "fk_ProviderAccount_ProviderId_Provider_ID" FOREIGN KEY ("ProviderId") REFERENCES "Provider" ("ID");
  END IF;
END $$;
