-- Generated by draw2sql
-- Flavor: oracle
-- Generated UTC: 2026-02-22T17:09:35.118Z


-- 1) Create missing tables

BEGIN
  EXECUTE IMMEDIATE q'[CREATE TABLE "Provider" (
  "ID" raw(16) NOT NULL,
  "Slug" varchar2(255),
  "Name" varchar2(255),
  "IsActive" number(1),
  "CreatedAt" timestamp,
  PRIMARY KEY ("ID")
)]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[CREATE TABLE "ProviderAccount" (
  "ID" raw(16) NOT NULL,
  "ProviderId" raw(16),
  "AccountKey" varchar2(255),
  "DisplayName" varchar2(255),
  "ExternalAccountId" varchar2(255),
  "IsActive" number(1),
  PRIMARY KEY ("ID")
)]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/


-- 2) Add missing columns

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
  FROM all_tab_cols
  WHERE table_name = 'PROVIDER'
    AND column_name = 'ID';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE "Provider" ADD ("ID" raw(16) NOT NULL)]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
  FROM all_tab_cols
  WHERE table_name = 'PROVIDER'
    AND column_name = 'SLUG';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE "Provider" ADD ("Slug" varchar2(255))]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
  FROM all_tab_cols
  WHERE table_name = 'PROVIDER'
    AND column_name = 'NAME';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE "Provider" ADD ("Name" varchar2(255))]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
  FROM all_tab_cols
  WHERE table_name = 'PROVIDER'
    AND column_name = 'ISACTIVE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE "Provider" ADD ("IsActive" number(1))]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
  FROM all_tab_cols
  WHERE table_name = 'PROVIDER'
    AND column_name = 'CREATEDAT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE "Provider" ADD ("CreatedAt" timestamp)]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
  FROM all_tab_cols
  WHERE table_name = 'PROVIDERACCOUNT'
    AND column_name = 'ID';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE "ProviderAccount" ADD ("ID" raw(16) NOT NULL)]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
  FROM all_tab_cols
  WHERE table_name = 'PROVIDERACCOUNT'
    AND column_name = 'PROVIDERID';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE "ProviderAccount" ADD ("ProviderId" raw(16))]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
  FROM all_tab_cols
  WHERE table_name = 'PROVIDERACCOUNT'
    AND column_name = 'ACCOUNTKEY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE "ProviderAccount" ADD ("AccountKey" varchar2(255))]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
  FROM all_tab_cols
  WHERE table_name = 'PROVIDERACCOUNT'
    AND column_name = 'DISPLAYNAME';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE "ProviderAccount" ADD ("DisplayName" varchar2(255))]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
  FROM all_tab_cols
  WHERE table_name = 'PROVIDERACCOUNT'
    AND column_name = 'EXTERNALACCOUNTID';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE "ProviderAccount" ADD ("ExternalAccountId" varchar2(255))]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
  FROM all_tab_cols
  WHERE table_name = 'PROVIDERACCOUNT'
    AND column_name = 'ISACTIVE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE "ProviderAccount" ADD ("IsActive" number(1))]';
  END IF;
END;
/


-- 3) Add foreign keys where inferred

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
  FROM all_constraints
  WHERE constraint_name = 'FK_PROVIDERACCOUNT_PROVIDERID_PROVIDER_ID';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[ALTER TABLE "ProviderAccount" ADD CONSTRAINT "fk_ProviderAccount_ProviderId_Provider_ID" FOREIGN KEY ("ProviderId") REFERENCES "Provider" ("ID")]';
  END IF;
END;
/
