-- Generated by draw2sql
-- Flavor: postgres
-- Table Name Style: db-default (snake)
-- Field Name Style: db-default (snake)
-- Generated UTC: 2026-03-01T21:53:40.456Z


-- 1) Create missing tables

CREATE TABLE IF NOT EXISTS "user" (
  "user_id" uuid NOT NULL,
  "user_name" text,
  "email" text,
  "phone" text,
  PRIMARY KEY ("user_id")
);

CREATE TABLE IF NOT EXISTS "role" (
  "role_id" uuid NOT NULL,
  "name" text,
  "description" text,
  "ad_group" text,
  PRIMARY KEY ("role_id")
);

CREATE TABLE IF NOT EXISTS "user_role" (
  "user_role_id" uuid NOT NULL,
  "user_id" uuid,
  "role_id" uuid,
  PRIMARY KEY ("user_role_id")
);

CREATE TABLE IF NOT EXISTS "perm_set" (
  "perm_set_id" uuid NOT NULL,
  "name" text,
  "description" text,
  PRIMARY KEY ("perm_set_id")
);

CREATE TABLE IF NOT EXISTS "permission" (
  "permission_id" uuid NOT NULL,
  "name" text,
  "description" text,
  PRIMARY KEY ("permission_id")
);

CREATE TABLE IF NOT EXISTS "perm_set_permission" (
  "perm_set_permission_id" uuid NOT NULL,
  "perm_set_id" uuid,
  "permission_id" uuid,
  PRIMARY KEY ("perm_set_permission_id")
);

CREATE TABLE IF NOT EXISTS "role_perm_set" (
  "role_perm_set_id" uuid NOT NULL,
  "role_id" uuid,
  "perm_set_id" uuid,
  PRIMARY KEY ("role_perm_set_id")
);


-- 2) Add missing columns

ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "user_id" uuid NOT NULL;

ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "user_name" text;

ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "email" text;

ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "phone" text;

ALTER TABLE "role" ADD COLUMN IF NOT EXISTS "role_id" uuid NOT NULL;

ALTER TABLE "role" ADD COLUMN IF NOT EXISTS "name" text;

ALTER TABLE "role" ADD COLUMN IF NOT EXISTS "description" text;

ALTER TABLE "role" ADD COLUMN IF NOT EXISTS "ad_group" text;

ALTER TABLE "user_role" ADD COLUMN IF NOT EXISTS "user_role_id" uuid NOT NULL;

ALTER TABLE "user_role" ADD COLUMN IF NOT EXISTS "user_id" uuid;

ALTER TABLE "user_role" ADD COLUMN IF NOT EXISTS "role_id" uuid;

ALTER TABLE "perm_set" ADD COLUMN IF NOT EXISTS "perm_set_id" uuid NOT NULL;

ALTER TABLE "perm_set" ADD COLUMN IF NOT EXISTS "name" text;

ALTER TABLE "perm_set" ADD COLUMN IF NOT EXISTS "description" text;

ALTER TABLE "permission" ADD COLUMN IF NOT EXISTS "permission_id" uuid NOT NULL;

ALTER TABLE "permission" ADD COLUMN IF NOT EXISTS "name" text;

ALTER TABLE "permission" ADD COLUMN IF NOT EXISTS "description" text;

ALTER TABLE "perm_set_permission" ADD COLUMN IF NOT EXISTS "perm_set_permission_id" uuid NOT NULL;

ALTER TABLE "perm_set_permission" ADD COLUMN IF NOT EXISTS "perm_set_id" uuid;

ALTER TABLE "perm_set_permission" ADD COLUMN IF NOT EXISTS "permission_id" uuid;

ALTER TABLE "role_perm_set" ADD COLUMN IF NOT EXISTS "role_perm_set_id" uuid NOT NULL;

ALTER TABLE "role_perm_set" ADD COLUMN IF NOT EXISTS "role_id" uuid;

ALTER TABLE "role_perm_set" ADD COLUMN IF NOT EXISTS "perm_set_id" uuid;


-- 3) Add foreign keys where inferred

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_role_user_id_user_user_id') THEN
    ALTER TABLE "user_role" ADD CONSTRAINT "fk_user_role_user_id_user_user_id" FOREIGN KEY ("user_id") REFERENCES "user" ("user_id");
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_role_role_id_role_role_id') THEN
    ALTER TABLE "user_role" ADD CONSTRAINT "fk_user_role_role_id_role_role_id" FOREIGN KEY ("role_id") REFERENCES "role" ("role_id");
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_perm_set_permission_perm_set_id_perm_set_perm_set_id') THEN
    ALTER TABLE "perm_set_permission" ADD CONSTRAINT "fk_perm_set_permission_perm_set_id_perm_set_perm_set_id" FOREIGN KEY ("perm_set_id") REFERENCES "perm_set" ("perm_set_id");
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_perm_set_permission_permission_id_permission_permission_id') THEN
    ALTER TABLE "perm_set_permission" ADD CONSTRAINT "fk_perm_set_permission_permission_id_permission_permission_id" FOREIGN KEY ("permission_id") REFERENCES "permission" ("permission_id");
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_role_perm_set_role_id_role_role_id') THEN
    ALTER TABLE "role_perm_set" ADD CONSTRAINT "fk_role_perm_set_role_id_role_role_id" FOREIGN KEY ("role_id") REFERENCES "role" ("role_id");
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_role_perm_set_perm_set_id_perm_set_perm_set_id') THEN
    ALTER TABLE "role_perm_set" ADD CONSTRAINT "fk_role_perm_set_perm_set_id_perm_set_perm_set_id" FOREIGN KEY ("perm_set_id") REFERENCES "perm_set" ("perm_set_id");
  END IF;
END $$;
